{% set name = "gdxpds" %}
{% set version = "1.4.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 3956e9fefec844d2727b11c43f5276a25fb2540ff6e4eb3e085239422f5ef2be

build:
#  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install --no-deps --no-build-isolation . -vv"

requirements:
  host:
    - gdxcc
    - numpy >=1.7
    - pandas >=0.20.1
    - pip
    - python
  run:
    - gdxcc
    - numpy >=1.7
    - pandas >=0.20.1
    - python

#test:
#  commands:
#    - pytest --pyargs gdxpds
#  imports:
#    - gdx-pandas
#    - gdxpds.test

about:
  home: "https://github.com/NREL/gdx-pandas"
  license: UNKNOWN
  license_family: OTHER
  license_file: 
  summary: "gdx-pandas is a python package to translate between gdx (GAMS data) and pandas"
  doc_url: 
  dev_url: 

extra:
  anaconda-services:
    ref: https://anaconda.zendesk.com/agent/tickets/46266
    reason: Client request
  recipe-maintainers:
    - ianaobi
    - bkreider
